AarhusWebDevCoop/ViewModels/ContactForm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AarhusWebDevCoop.ViewModels
{
    public class ContactForm
    {
        [Required(ErrorMessage ="Please enter your name")]
        public string Name { get; set; }
        [Required(ErrorMessage = "Please enter your mail")]
        [Display(Name ="Email")]
        [RegularExpression(@"^([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)$", ErrorMessage = "Please enter a correct e-mail adress")]
        public string Email { get; set; }
        [Required(ErrorMessage = "Please enter a subject")]
        public string Subject { get; set; }
        [Required(ErrorMessage = "Please enter a message")]
        public string Message { get; set; }
    }


}

AarhusWebDevCoop/Controllers/ContactFormSurfaceController.cs
using AarhusWebDevCoop.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using Umbraco.Core.Models;
using Umbraco.Core.Services;

namespace AarhusWebDevCoop.Controllers
{
    public class ContactFormSurfaceController : SurfaceController
    {
        // GET: ContactFormSurface
        public ActionResult Index()
        {
            return PartialView("ContactPagePartial", new ContactForm());
        }

        [HttpPost]
        public ActionResult CreateContent(ContactForm model)
        {
            return RedirectToCurrentUmbracoPage();
        }

        [HttpPost]
        public ActionResult HandleFormSubmit(ContactForm model)
        {

            if (!ModelState.IsValid)
            {
                return CurrentUmbracoPage();
            }

            MailMessage message = new MailMessage();
            message.To.Add("rene1988dahl@gmail.com");
            message.Subject = model.Subject;
            message.From = new MailAddress(model.Email, model.Name);
            message.Body = model.Message;


            using (SmtpClient smtp = new SmtpClient())
            {
                smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
                smtp.UseDefaultCredentials = false;
                smtp.EnableSsl = true;
                smtp.Host = "smtp.gmail.com";
                smtp.Port = 587;
                smtp.Credentials = new System.Net.NetworkCredential("rene1988dahl@gmail.com", "IsAllowed!");
                // send mail
               smtp.Send(message);
            }

            

            IContent comment = Services.ContentService.CreateContent(model.Subject, CurrentPage.Id, "message");
            comment.SetValue("messageName", model.Name);
            comment.SetValue("email", model.Email);
            comment.SetValue("subject", model.Subject);
            comment.SetValue("messageContent", model.Message);

            Services.ContentService.Save(comment);
          //  Services.ContentService.SaveAndPublishWithStatus(comment);





            TempData["success"] = true;


            return RedirectToCurrentUmbracoPage();
        }

     
    }
}

AarhusWebDevCoop/Views/AboutUs.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.AboutUs>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

<div>
    @Html.GetGridHtml(Model.Content, "gridlayout")

</div>

AarhusWebDevCoop/Views/ArticleItem.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ArticleItem>
@{
	Layout = "Master.cshtml";
}


<h1>
    @Model.ArticleTitle
   
</h1>

<p>
    @Model.ArticleContent

    
</p>

AarhusWebDevCoop/Views/ArticlesOverview.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ArticlesOverview>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

@* the fun starts here *@

@Model.ArticlesTitle

@Umbraco.RenderMacro("listArticles")

AarhusWebDevCoop/Views/ContactPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<ContactPage>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}


<h2>
   @Model.Name
</h2>

<div>

    @Html.Action("Index", "ContactFormSurface")

</div>

AarhusWebDevCoop/Views/HomePage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage<Homepage>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    Layout = "Master.cshtml";
}



<div class="container">




    <div class="col-md-8">
        <h1></h1>
        @Model.MainContent
    </div>

    <div class="col-md-4">

       
                <p><b>Nyeste projekter</b></p>
                @Umbraco.RenderMacro("listNewestProjects", new { NumOfProjects = "3" })
       
    </div>




</div>

AarhusWebDevCoop/Views/Login.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Login>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    Layout = "Master.cshtml";
}



@Html.Partial("loginForm")

AarhusWebDevCoop/Views/MacroPartials/listArticles.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@using Umbraco.Web


@*
    This snippet makes a list of links to the of children of the current page using an unordered HTML list.

    How it works:
    - It uses the Children method to get all child pages
    - It then uses the OrderByDescending() method, which takes the property to sort. In this case the page's creation date.
    - It then generates links so the visitor can go to each page
*@

@{ var selection = Model.Content.Children.Where(x => x.IsVisible()).OrderByDescending(x => x.CreateDate).ToArray(); }

@if (selection.Length > 0)
{
    <ul>
        @foreach (var item in selection)
        {
            <li><a href="@item.Url">@item.Name</a></li>
        }
    </ul>
}

AarhusWebDevCoop/Views/MacroPartials/listNewestProjects.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage

@{



var NumOfProjects = Model.MacroParameters["NumOfProjects"];


IPublishedContent[] selection =
Model.Content.AncestorOrSelf(1)
.Children()
.Where(x => x.DocumentTypeAlias == "projectsOverview")
.First()
.Children
.Where(x => x.HasValue("projectStatus") && Umbraco.GetPreValueAsString(x.GetPropertyValue<int>("projectStatus")) == "Completed")
.OrderBy(x => x.CreateDate).Take(Convert.ToInt32(NumOfProjects))

.ToArray();

}
<ul>
    @foreach (IPublishedContent item in selection)
    {
        <li>
            <a href="@item.Url">@item.Name</a>
        </li>
    }


</ul>

AarhusWebDevCoop/Views/MacroPartials/listProjects.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@using Umbraco.Web


@*
    This snippet makes a list of links to the of children of the current page using an unordered HTML list.

    How it works:
    - It uses the Children method to get all child pages
    - It then uses the OrderByDescending() method, which takes the property to sort. In this case the page's creation date.
    - It then generates links so the visitor can go to each page
*@

@{ var selection = Model.Content.Children.Where(x => x.IsVisible()).OrderByDescending(x => x.CreateDate).ToArray(); }

@if (selection.Length > 0)
{
    <ul>
        @foreach (var item in selection)
        {
            <li><a href="@item.Url">@item.Name</a></li>
        }
    </ul>
}

AarhusWebDevCoop/Views/MacroPartials/listProjectsDropdown.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage

@{

    IPublishedContent[] projectDropdown =
    Model.Content.AncestorOrSelf(1)
     .Children()
     .Where(x => x.DocumentTypeAlias == "projectsOverview")
     .First()
     .Children()
     .ToArray();



}

<ul>
    @foreach (IPublishedContent page in projectDropdown)        
    {
        <li>@page.Name</li>
    }
</ul>




                

AarhusWebDevCoop/Views/MacroPartials/loginForm.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage


@using System.Web.Mvc.Html
@using ClientDependency.Core.Mvc
@using Umbraco.Web
@using Umbraco.Web.Models
@using Umbraco.Web.Controllers

@{
    var loginModel = new LoginModel();
    
    Html.EnableClientValidation();
    Html.EnableUnobtrusiveJavaScript();
    Html.RequiresJs("/umbraco_client/ui/jquery.js");
    Html.RequiresJs("/umbraco_client/Application/JQuery/jquery.validate.min.js");
    Html.RequiresJs("/umbraco_client/Application/JQuery/jquery.validate.unobtrusive.min.js");
}

@* NOTE: This RenderJsHere code should be put on your main template page where the rest of your script tags are placed *@
@Html.RenderJsHere()

@using (Html.BeginUmbracoForm<UmbLoginController>("HandleLogin"))
{
    <fieldset>
        <legend>Login</legend>
        
        @Html.ValidationSummary("loginModel", true)

        @Html.LabelFor(m => loginModel.Username)
        @Html.TextBoxFor(m => loginModel.Username)
        @Html.ValidationMessageFor(m => loginModel.Username)
        <br />

        @Html.LabelFor(m => loginModel.Password)
        @Html.PasswordFor(m => loginModel.Password)
        @Html.ValidationMessageFor(m => loginModel.Password)
        <br />

        <button>Login</button>
    </fieldset>  
}

AarhusWebDevCoop/Views/MacroPartials/mainMenu.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@using Umbraco.Web

@{
    //Main navigation

    var root = Model.Content.Site();
    var selection = root.Children.Where(x => x.IsVisible()).ToArray();



}

@{
    //Dropdown menu!

IPublishedContent[] projectDropdown =
Model.Content.AncestorOrSelf(1)
.Children()
.Where(x => x.DocumentTypeAlias == "projectsOverview")
.First()
.Children()
.Where(x => x.HasValue("projectStatus") && Umbraco.GetPreValueAsString(x.GetPropertyValue<int>("projectStatus")) == "Completed")
.Where(x => x.IsVisible())
.ToArray();

}


<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">@Umbraco.Field("siteTitle", recursive: true)</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">

            <!--The first note comes here, the root element is the first.-->
            <li class="nav-item @(Model.Content.Name == root.Name ? "current" : null)">
                <a class="nav-link" href="@root.Url">@root.Name</a>
            </li>

            @if (selection.Length > 0)
            {


                foreach (var item in selection)
                {
                    <li class="@(item.IsAncestorOrSelf(Model.Content) ? "current": null) nav-item">
                        <a href="@item.Url" class="nav-link">@item.Name</a>
                    </li>
                }


                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Projects
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        @if (selection.Length > 0)
                        {
                            foreach (var menuItem in projectDropdown.Where("UmbracoNavHide == false"))
                            {
                                var isProtected = umbraco.library.IsProtected(menuItem.Id, menuItem.Path);
                                var loginAccess = isProtected && umbraco.library.HasAccess(menuItem.Id, menuItem.Path);

                                if (!isProtected || loginAccess)
                                {
                                    <a class="dropdown-item" href="@menuItem.Url">@menuItem.Name</a>
                                }


                            }

                        }



                    </div>
                </li>



            }
        </ul>
    </div>


</nav>

AarhusWebDevCoop/Views/MacroPartials/sitemap.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@using Umbraco.Core.Models
@using Umbraco.Web


@*
    This snippet makes a list of links of all visible pages of the site, as nested unordered HTML lists.

    How it works:
    - It uses a custom Razor helper called Traverse() to select and display the markup and links.
*@

@{ var selection = Model.Content.Site(); }

<div class="sitemap">
    @* Render the sitemap by passing the root node to the traverse helper, below *@
    @Traverse(selection)
</div>


@* Helper method to traverse through all descendants *@
@helper Traverse(IPublishedContent node)
{
    @* Update the level to reflect how deep you want the sitemap to go *@
    const int maxLevelForSitemap = 4;

    @* Select visible children *@
    var selection = node.Children.Where(x => x.IsVisible() && x.Level <= maxLevelForSitemap).ToArray();

    @* If any items are returned, render a list *@
    if (selection.Length > 0)
    {
        <ul>
            @foreach (var item in selection)
            {
                <li class="level-@item.Level">
                    <a href="@item.Url">@item.Name</a>

                    @* Run the traverse helper again for any child pages *@
                    @Traverse(item)
                </li>
            }
        </ul>
    }
}

AarhusWebDevCoop/Views/Master.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Master>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
    <title>@Umbraco.Field("titleTag") | Arhus Web Developer Corporation </title>
    <meta name="description" content="@Umbraco.Field("metaDescription")">
    <meta name="keywords" content="@Umbraco.Field("metaKeywords")">

    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

</head>

<body>



    @Umbraco.RenderMacro("mainMenu")
    <div class="container">
        @RenderBody()




    </div>

    <div class="footer fixed-bottom">
        @Umbraco.Field("footer", recursive: true)
    </div>

    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>

    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
</body>

</html>

AarhusWebDevCoop/Views/Members.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Members>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@using Umbraco.Web
@using Newtonsoft.Json;
@using Umbraco.Web.Models;
@{
    Layout = "Master.cshtml";

}

@{
    var memberService = ApplicationContext.Current.Services.MemberService;
    var members = memberService.GetMembersByGroup("Active");

    foreach (var member in members)
    {
        <p>
            @member.Name
            <br>@member.GetValue("address")
            <br>@member.GetValue("zip")
            @member.GetValue("city")
            @member.GetValue("city")
            <br>Email: @member.Email<br>
        </p>

        if (member.GetValue("skills") != null)
        {
            string[] skills = member.GetValue("skills").ToString().Split(',');
            string skillString = string.Join(", ", from skill in skills select umbraco.library.GetPreValueAsString(Convert.ToInt32(skill)));

            <span>Skills: @skillString</span>
        }

    if (member.GetValue("photo") != null)
    {
        string image = member.GetValue<string>("photo");

        if (image != null)
        {
            ImageCropDataSet imageCrop = JsonConvert.DeserializeObject<ImageCropDataSet>(image);

           

        <img src="@imageCrop" alt="Alternate Text" />

        }




    }

}



}

AarhusWebDevCoop/Views/Message.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Message>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
}

AarhusWebDevCoop/Views/Partials/ContactPagePartial.cshtml
@model AarhusWebDevCoop.ViewModels.ContactForm
@{
    Layout = null;
}

@if (TempData["success"] == null)
{
    //Display the form

    using (Html.BeginUmbracoForm("HandleFormSubmit", "ContactFormSurface", new object { }, new { @class = "form-horizontal" }))
    {
        <div class="form-group">
            @Html.LabelFor(m => m.Name, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "Name" })
                @Html.ValidationMessageFor(m => m.Name)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Email, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Email address" })
                @Html.ValidationMessageFor(m => m.Email)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Subject, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.Subject, new { @class = "form-control", placeholder = "Subject" })
                @Html.ValidationMessageFor(m => m.Subject)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.Message, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-6">
                @Html.TextAreaFor(m => m.Message, new { @class = "form-control", placeholder = "Your message" })
                @Html.ValidationMessageFor(m => m.Message)
            </div>
        </div>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-6">
                <button id="contact-submit" type="submit" class="btn btn-primary input-medium pull-left">Send</button>
            </div>
        </div>

    }

}

else
{
    <p>Thank you for contacting us. We’ll be in touch soon!</p>
}

AarhusWebDevCoop/Views/Partials/Grid/Bootstrap2-Fluid.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container-fluid">
                <div class="row-fluid clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="@("span" + s.grid) column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container-fluid'>")
        <div class="row-fluid clearfix">
            @foreach ( var area in row.areas ) {
            <div class="@("span" + area.grid) column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style='" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "'");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

AarhusWebDevCoop/Views/Partials/Grid/Bootstrap2.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="@("span" + s.grid) column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="@("span" + area.grid) column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style=\"" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "\"");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

AarhusWebDevCoop/Views/Partials/Grid/Bootstrap3-Fluid.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row);
                    }
                </div>
            }   
        }else { 
            <div class="row clearfix">
                @foreach (var s in Model.sections) {
                    <div class="grid-section">
                        <div class="col-md-@s.grid column">
                            @foreach (var row in s.rows) {
                                @renderRow(row);
                            }
                        </div>
                    </div>
                }
            </div>
        }
    </div>
}

@helper renderRow(dynamic row){
    <div @RenderElementAttributes(row)>
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="col-md-@area.grid column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties())
            {
                var propertyValue = HttpUtility.HtmlAttributeEncode(property.Value.ToString());
                attrs.Add(property.Name + "=\"" + propertyValue + "\"");
            }

        JObject style = contentItem.styles;

        if (style != null) {
            var cssVals = new List<string>();
            foreach (JProperty property in style.Properties())
            {
                var propertyValue = property.Value.ToString();
                if (string.IsNullOrWhiteSpace(propertyValue) == false)
                {
                    cssVals.Add(property.Name + ":" + propertyValue + ";");
                }
            }

            if (cssVals.Any())
                attrs.Add("style='" + HttpUtility.HtmlAttributeEncode(string.Join(" ", cssVals)) + "'");
        }

        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

AarhusWebDevCoop/Views/Partials/Grid/Editors/Base.cshtml
@model dynamic
@using Umbraco.Web.Templates

@functions {
    public static string EditorView(dynamic contentItem)
    {
        string view = contentItem.editor.render != null ? contentItem.editor.render.ToString() : contentItem.editor.view.ToString();
        view = view.ToLower().Replace(".html", ".cshtml");
        
        if (!view.Contains("/")) {
            view = "grid/editors/" + view;
        }

        return view;
    }
}
@try
{
    string editor = EditorView(Model);                                                       
    <text>@Html.Partial(editor, (object)Model)</text>
}
catch (Exception ex) { 
<pre>@ex.ToString()</pre>
}

AarhusWebDevCoop/Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@using Umbraco.Web.Templates


<div class="video-wrapper">
	@Html.Raw(Model.value)
</div>

AarhusWebDevCoop/Views/Partials/Grid/Editors/Macro.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates


@if (Model.value != null)
{
    string macroAlias = Model.value.macroAlias.ToString();
    ViewDataDictionary parameters = new ViewDataDictionary();
    foreach (dynamic mpd in Model.value.macroParamsDictionary)
    {
        parameters.Add(mpd.Name, mpd.Value);
    }

    <text>
        @Umbraco.RenderMacro(macroAlias, parameters)
    </text>
}

AarhusWebDevCoop/Views/Partials/Grid/Editors/Media.cshtml
@model dynamic
@using Umbraco.Web.Templates

@if (Model.value != null)
{   
    var url = Model.value.image;
    if(Model.editor.config != null && Model.editor.config.size != null){
        url += "?width=" + Model.editor.config.size.width;
        url += "&height=" + Model.editor.config.size.height;

        if(Model.value.focalPoint != null){
            url += "&center=" + Model.value.focalPoint.top +"," + Model.value.focalPoint.left;
            url += "&mode=crop";
        }
    }

    var altText = Model.value.altText ?? Model.value.caption ?? string.Empty;
    
    <img src="@url" alt="@altText">
    
    if (Model.value.caption != null)
    {
        <p class="caption">@Model.value.caption</p>
    }
}